#  Numpy 

Numpy es una biblioteca de python para trabajar con matrices de n dimensiones. Esto permite llevar a cabo operaciones matematicas de algebra lineal, estadistica, simulacion, procesamiento de imagenes, respecto a las matrices estandar de python, las de numpy permiten obtener un mayor rendimiento.

Github
Web oficial
Grupo de desarrollo
Soporte



In [1]:
# importacion
import numpy as np

In [2]:
np.__version__

'1.11.3'

In [7]:
#creacion de un array
x = [2, 3, 4, 6]
y = np.array(x)

In [12]:
print type(x)
print type(y)
print y.dtype

<type 'list'>
<type 'numpy.ndarray'>
int64


In [21]:
# especificando el tipo de datos que contiene
# complejo
z = np.array([(1.5,2,3), (4,5,6)],dtype=int)
z

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# especificando el tipo de datos que contiene
# complejo
z = np.array([(1.5,2,3), (4,5,6)],dtype=complex)
z

array([[ 1.5+0.j,  2.0+0.j,  3.0+0.j],
       [ 4.0+0.j,  5.0+0.j,  6.0+0.j]])

Matrices de uso frecuente

In [23]:
# Matriz de ceros
a=np.zeros((3,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
#Matriz de unos
a=np.ones((2,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [28]:
# secuencia desde el 10 al 50 aumento de 5
np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [30]:
#dar tamaño
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [35]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Seleccion de datos

In [37]:
a=np.arange(6).reshape(2,3)
b=np.arange(4).reshape(2,2)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
a[0,0:2]

array([0, 1])

In [39]:
a[:,0:1]

array([[0],
       [3]])

In [49]:
a[a>=2]

array([2, 3, 4, 5])

In [56]:
a>=2

array([[False, False,  True],
       [ True,  True,  True]], dtype=bool)

Operaciones

In [51]:
a*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [52]:
a/2

array([[0, 0, 1],
       [1, 2, 2]])

In [57]:
a**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [58]:
a*np.pi

array([[  0.        ,   3.14159265,   6.28318531],
       [  9.42477796,  12.56637061,  15.70796327]])

In [59]:
a.sum()

15

In [60]:
a.min()

0

In [61]:
a.mean()

2.5

In [62]:
#suma de columnas
a.sum(axis=0)

array([3, 5, 7])

In [ ]:
#suma de filas

In [64]:
#suma de columnas
a.sum(axis=1)

array([ 3, 12])

In [55]:
# Multiplicación de matrices
np.dot(b,a)

array([[ 3,  4,  5],
       [ 9, 14, 19]])