Regresion multiple y generalizacion

In [1]:
# importacion de modulos
import scipy as sp
import pandas as pd
import numpy as np
import sklearn as sk
from matplotlib import pylab as plt
%matplotlib inline

In [60]:
data=pd.read_csv("ventas.csv",index_col=0)

In [61]:
data.head()

TV  Radio  Periodico  Ventas
1  230.1   37.8       69.2    22.1
2   44.5   39.3       45.1    10.4
3   17.2   45.9       69.3     9.3
4  151.5   41.3       58.5    18.5
5  180.8   10.8       58.4    12.9

In [123]:
X=data[['TV','Radio','Periodico']]
X.insert(0,'uno',1)
y=data[['Ventas']]

In [124]:
print y.shape , X.shape

(200, 1) (200, 4)


$f(x)=w_0+\sum_{j=1}{X_jw_j}$

$RSS(w)=\sum_{i=1}{(y_i-f(x_i))^2}$

$RSS(w)=\sum_{i=1}{(y_i-w_0-\sum_{j=1}{x_{ij}w_j})^2}$

Matricialmente:

$ RSS(w)=(y-Xw)^T(y-Xw)$



$w=(X^TX)^{-1}X^Ty$

In [132]:
from numpy.linalg import inv
def pesos(X,y):
    return np.dot(np.dot(inv(np.dot(X.T,X)),X.T),y)

In [133]:
w=pesos(X,y)

In [141]:
def pred(v,w,i=True):
    if i==True:
        p=np.dot(v,w)
    if i==False:
        v=np.insert(v,0,1)
        p=np.dot(v,w)
    return p

In [142]:
pred([1,2,3],w,i=False)

array([ 3.35860157])

error

Importacion de sklearn

[Lineal Model Scikit-learn](https://scikit-learn.org/stable/modules/linear_model.html)

In [35]:
X_entrenamiento, X_prueba, y_entrenamiento, y_prueba = sk.cross_validation.train_test_split(X, y, random_state=1)

In [37]:
print X_entrenamiento.shape,X_prueba.shape,y_entrenamiento.shape,y_prueba.shape

(150, 3) (50, 3) (150, 1) (50, 1)


In [43]:
from sklearn.linear_model import LinearRegression
reg_lineal =LinearRegression()
reg_lineal.fit(X_entrenamiento, y_entrenamiento)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [44]:
reg_lineal.intercept_

array([ 2.87696662])

In [45]:
reg_lineal.coef_

array([[ 0.04656457,  0.17915812,  0.00345046]])

In [138]:
y_pred = reg_lineal.predict(X_test)

NameError: name 'reg_lineal' is not defined

In [1]:
import statsmodels.formula.api as smf

La regresión lineal se puede generalizar tomando en cuenta transformaciones segun funciones de los imputs:
